[package]
name = "rs_lib"
version = "0.0.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]
path = "./lib.rs"

[dependencies]
console_static_text = "0.8.3"
js-sys = "=0.3.77"
serde = "1"
serde-wasm-bindgen = "=0.6.5"
wasm-bindgen = "=0.2.100"
